### ISSUE TITLE
Running debianUpdateNotification.js on orange Pi Plus 2e causes error

### ISSUE THREAD

**Issue by Marty56** [foxriver76/iot-blog-scripts#1]
Running your script on an orange Pi Plus 2e causes error.

`

host.ioBroker-OPi2E | 2019-02-02 13:06:58.873 | error | instance system.adapter.javascript.0 terminated with code 0 (OK)
-- | -- | -- | --
host.ioBroker-OPi2E | 2019-02-02 13:06:58.872 | error | Caught by controller[0]:     at Pipe._handle.close [as _onclose] (net.js:509:12)
host.ioBroker-OPi2E | 2019-02-02 13:06:58.871 | error | Caught by controller[0]:     at Socket.emit (events.js:188:7)
host.ioBroker-OPi2E | 2019-02-02 13:06:58.871 | error | Caught by controller[0]:     at emitOne (events.js:96:13)
host.ioBroker-OPi2E | 2019-02-02 13:06:58.871 | error | Caught by controller[0]:     at Socket.<anonymous> (internal/child_process.js:351:11)
host.ioBroker-OPi2E | 2019-02-02 13:06:58.870 | error | Caught by controller[0]:     at maybeClose (internal/child_process.js:920:16)
host.ioBroker-OPi2E | 2019-02-02 13:06:58.870 | error | Caught by controller[0]:     at ChildProcess.emit (events.js:191:7)
host.ioBroker-OPi2E | 2019-02-02 13:06:58.870 | error | Caught by controller[0]:     at emitTwo (events.js:106:13)
host.ioBroker-OPi2E | 2019-02-02 13:06:58.869 | error | Caught by controller[0]:     at ChildProcess.exithandler (child_process.js:206:5)
host.ioBroker-OPi2E | 2019-02-02 13:06:58.869 | error | Caught by controller[0]:     at exec (script.js.test.Test2:33:23)
host.ioBroker-OPi2E | 2019-02-02 13:06:58.867 | error | Caught by controller[0]: TypeError: Cannot read property 'length' of undefined
javascript.0 | 2019-02-02 13:06:58.781 | error | TypeError: Cannot read property 'length' of undefined     at exec (script.js.test.Test2:33:23)     at ChildProcess.exithandler (child_process.js:206:5)     at emitTwo (events.js:106:13)     at ChildPr
javascript.0 | 2019-02-02 13:06:58.780 | error | uncaught exception: Cannot read property 'length' of undefined
`

I also tried to run the exec on the command line and received:
`root@ioBroker-OPi2E:~# apt update >/dev/null && apt list --upgradeable

WARNING: apt does not have a stable CLI interface. Use with caution in scripts.

W: GPG error: https://dl.bintray.com/mpmc/deb raspbianstretch Release: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 379CE192D401AB61
E: The repository 'https://dl.bintray.com/mpmc/deb raspbianstretch Release' is not signed.
W: GPG error: https://dl.bintray.com/mpmc/deb raspbianjessie Release: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 379CE192D401AB61
E: The repository 'https://dl.bintray.com/mpmc/deb raspbianjessie Release' is not signed.`

**Comment by foxriver76** [comment]
Please have a look at https://chrisjean.com/fix-apt-get-update-the-following-signatures-couldnt-be-verified-because-the-public-key-is-not-available/ 

or debian specific: https://ccm.net/faq/809-debian-apt-get-no-pubkey-gpg-error
